# Generated by Django 3.2.18 on 2023-04-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_app', '0002_auto_20230428_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=10),
        ),
    ]
