# Generated by Django 3.2.18 on 2023-04-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_app', '0003_auto_20230428_0749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city_name', 'state')},
        ),
    ]
