# Generated by Django 3.2.18 on 2023-04-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_app', '0004_alter_city_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busservice',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_service_destination', to='ticketing_app.city'),
        ),
        migrations.AlterField(
            model_name='busservice',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_service_source', to='ticketing_app.city'),
        ),
    ]
