# Generated by Django 3.2.18 on 2023-04-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_app', '0007_auto_20230428_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
