# Generated by Django 3.2.18 on 2023-04-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_app', '0008_alter_booking_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.BinaryField(null=True),
        ),
    ]
