# Generated by Django 3.2.18 on 2023-04-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_app', '0009_booking_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='qr_code',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
