# Generated by Django 3.2.18 on 2023-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_app', '0010_alter_booking_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='qr_code',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
